/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inventorycontrolsystem.view;

import com.mycompany.inventorycontrolsystem.db.DAOFactory;
import com.mycompany.inventorycontrolsystem.model.Category;
import com.mycompany.inventorycontrolsystem.model.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;
import java.util.concurrent.ExecutionException;

/**
 * Category Management screen.
 * NetBeans JPanel Form — GUI Builder designed.
 * Business logic is wired below the locked initComponents() block.
 */
public class CategoryFrame extends javax.swing.JPanel {
    private final User currentUser;
    private Category editingCategory = null;
    private DefaultTableModel liveTableModel;

    /**
     * Called by DashboardFrame when the user clicks "Categories" in the sidebar.
     *
     * @param user the authenticated session user
     */
    public CategoryFrame(User user) {
        this.currentUser = user;
        initComponents();     // NetBeans locked block — do not touch
        setupData();        // wire up all backend logic after GUI is built
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCurrentUser = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlTable = new javax.swing.JTable();
        pnlForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setBackground(new java.awt.Color(15, 23, 42));
        setMaximumSize(new java.awt.Dimension(1307, 757));
        setMinimumSize(new java.awt.Dimension(1307, 757));
        setPreferredSize(new java.awt.Dimension(1307, 757));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 36)); // NOI18N
        jLabel1.setText("Category Management");

        lblCurrentUser.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        lblCurrentUser.setText("User :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                        .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1290, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Category List"));

        pnlTable.setForeground(new java.awt.Color(0, 0, 0));
        pnlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Category ID", "Category Name"
            }
        ));
        jScrollPane1.setViewportView(pnlTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1)
                .addGap(84, 84, 84))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 630, 550));

        pnlForm.setBorder(javax.swing.BorderFactory.createTitledBorder("Category Details"));

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel2.setText("Category ID:");

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel3.setText("Category Name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtId.setEditable(false);

        btnDelete.setBackground(new java.awt.Color(153, 0, 0));
        btnDelete.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnDelete.setText("Delete");

        btnSave.setBackground(new java.awt.Color(0, 102, 255));
        btnSave.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnSave.setText("Save");

        btnClear.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnClear.setText("Clear");

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnSave)
                .addGap(122, 122, 122)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(61, 61, 61))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnSave)
                    .addComponent(btnClear))
                .addGap(78, 78, 78))
        );

        add(pnlForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 650, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // Enter key in txtName triggers Save — same as clicking btnSave
        onSaveClicked();
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lblCurrentUser;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JTable pnlTable;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
    // BACKEND INITIALISATION
    // Called once from the constructor after initComponents().

    /**
     * Wires up everything that initComponents() cannot do:
     *   - replaces the static table model with a live DefaultTableModel
     *   - displays the logged-in user name in lblCurrentUser
     *   - styles the table header
     *   - attaches all ActionListeners to the three buttons
     *   - kicks off the first async data load
     */
    private void setupData() {
        lblCurrentUser.setText("User:  " + currentUser.getFullName()
                + "  [" + getRoleName(currentUser.getRoleId()) + "]");
        lblCurrentUser.setEditable(false);
        lblCurrentUser.setBorder(null);
        lblCurrentUser.setOpaque(false);
        //    Columns match exactly what the Design Tab shows: ID | Name
        liveTableModel = new DefaultTableModel(
                new String[]{"Category ID", "Category Name"}, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;   // entire table is read-only; editing via the form
            }
            @Override
            public Class<?> getColumnClass(int col) {
                return col == 0 ? Integer.class : String.class;
            }
        };
        pnlTable.setModel(liveTableModel);
        pnlTable.getTableHeader().setFont(
                new Font("JetBrains Mono", Font.BOLD, 14));
        pnlTable.getTableHeader().setBackground(new Color(22, 43, 74));
        pnlTable.getTableHeader().setForeground(Color.WHITE);
        pnlTable.setRowHeight(28);
        pnlTable.setFont(new Font("JetBrains Mono", Font.PLAIN, 13));
        pnlTable.setSelectionBackground(new Color(41, 98, 178));
        pnlTable.setSelectionForeground(Color.WHITE);
        pnlTable.setGridColor(new Color(218, 224, 235));
        pnlTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Give the ID column a fixed narrow width
        pnlTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        pnlTable.getColumnModel().getColumn(0).setMaxWidth(140);
        pnlTable.getColumnModel().getColumn(1).setPreferredWidth(460);
        pnlTable.getTableHeader().setUI(
                new javax.swing.plaf.basic.BasicTableHeaderUI());
        pnlTable.getTableHeader().setFont(
                new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        pnlTable.getTableHeader().setBackground(
                new java.awt.Color(34, 45, 65));
        pnlTable.getTableHeader().setForeground(java.awt.Color.WHITE);
        pnlTable.getTableHeader().setReorderingAllowed(false);
        pnlTable.setRowHeight(28);
        pnlTable.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        //    Style it to make that visually obvious
        txtId.setBackground(new Color(230, 230, 230));
        txtId.setDisabledTextColor(Color.DARK_GRAY);
        txtId.setFont(new Font("JetBrains Mono", Font.PLAIN, 14));
        txtId.setToolTipText("Auto-generated — cannot be edited");
        btnSave  .addActionListener(e -> onSaveClicked());
        btnClear .addActionListener(e -> clearForm());
        btnDelete.addActionListener(e -> onDeleteClicked());

        // Row click → populate form fields
        pnlTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) onRowSelected();
        });
        loadCategoriesAsync();
    }
    // DATA LOADING — SwingWorker

    /**
     * Fetches all categories from the database on a background thread,
     * then populates {@code pnlTable} on the EDT.
     * Called on startup and after every save / delete operation.
     */
    private void loadCategoriesAsync() {
        new SwingWorker<List<Category>, Void>() {

            @Override
            protected List<Category> doInBackground() {
                return DAOFactory.getCategoryDAO().findAll();
            }

            @Override
            protected void done() {
                try {
                    List<Category> categories = get();
                    liveTableModel.setRowCount(0);      // clear existing rows

                    for (Category c : categories) {
                        liveTableModel.addRow(new Object[]{
                            c.getCategoryId(),
                            c.getCategoryName()
                        });
                    }

                    // Auto-resize columns after data is populated
                    autoResizeColumns(pnlTable);

                } catch (ExecutionException ex) {
                    ex.getCause().printStackTrace();
                    JOptionPane.showMessageDialog(
                            CategoryFrame.this,
                            "Could not load categories.\nCheck database connection.",
                            "Load Error", JOptionPane.ERROR_MESSAGE);
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                }
            }
        }.execute();
    }
    // EVENT HANDLERS

    /**
     * Row click handler — reads the selected row and populates the form fields.
     * txtId shows the category_id (read-only).
     * txtName shows the category name (editable for updates).
     */
    private void onRowSelected() {
        int row = pnlTable.getSelectedRow();
        if (row < 0) return;

        int    id   = (int)    liveTableModel.getValueAt(row, 0);
        String name = (String) liveTableModel.getValueAt(row, 1);

        // Load the full Category object so we have all fields for the update
        DAOFactory.getCategoryDAO().findById(id).ifPresent(c -> {
            editingCategory = c;
            txtId  .setText(String.valueOf(c.getCategoryId()));
            txtName.setText(c.getCategoryName());
            System.out.println("Row selected → category ID={}");
        });
    }

    /**
     * Save button handler.
     * Inserts a new category when {@code editingCategory} is null,
     * or updates the existing one when a row was previously selected.
     *
     * Validation rules:
     *   - Category Name must not be blank.
     */
    private void onSaveClicked() {
        String name = txtName.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Category Name cannot be empty.",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtName.requestFocusInWindow();
            return;
        }
        boolean isNew = (editingCategory == null);
        Category c = isNew ? new Category() : editingCategory;
        c.setCategoryName(name);
        c.setActive(true);
        boolean success;
        if (isNew) {
            success = DAOFactory.getCategoryDAO().insert(c) > 0;
        } else {
            success = DAOFactory.getCategoryDAO().update(c);
        }

        if (success) {
            String action = isNew ? "added" : "updated";
            JOptionPane.showMessageDialog(this,
                    "Category '" + name + "' saved successfully.",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            clearForm();
            loadCategoriesAsync();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Save failed. The category name may already exist.\n"
                    + "Check the application log for details.",
                    "Save Failed", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Delete button handler.
     * Requires a row to be selected first.
     * Shows a confirmation dialog before calling the DAO.
     *
     * Note: deletion will fail if products are linked to this category
     * (enforced by the FK constraint in MySQL).
     */
    private void onDeleteClicked() {
        int row = pnlTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select a category from the table first.",
                    "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int    id   = (int)    liveTableModel.getValueAt(row, 0);
        String name = (String) liveTableModel.getValueAt(row, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Delete category:  \"" + name + "\"?\n\n"
                + "WARNING: This will fail if products are assigned to this category.",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean ok = DAOFactory.getCategoryDAO().delete(id);
            if (ok) {
                clearForm();
                loadCategoriesAsync();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Delete failed.\n"
                        + "This category may have products assigned to it.\n"
                        + "Reassign or deactivate those products first.",
                        "Delete Failed", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    // FORM HELPERS

    /**
     * Resets all form fields and clears the table selection.
     * Sets the state back to "adding a new category".
     */
    private void clearForm() {
        editingCategory = null;
        txtId  .setText("");
        txtName.setText("");
        pnlTable.clearSelection();
        txtName.requestFocusInWindow();
    }

    /** Returns a human-readable role name from a numeric role ID. */
    private String getRoleName(int roleId) {
        return switch (roleId) {
            case 1  -> "Admin";
            case 2  -> "Manager";
            default -> "Cashier";
        };
    }

    /**
     * Resizes every column to fit both its header text and the widest
     * cell value currently in the table.
     * Called from SwingWorker.done() so row data is present when measured.
     *
     * @param table the JTable to auto-size (null-safe)
     */
    private void autoResizeColumns(javax.swing.JTable table) {
        if (table == null) return;
        final javax.swing.table.TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 50; // minimum

            // Measure header
            javax.swing.table.TableCellRenderer headerRenderer =
                table.getTableHeader().getDefaultRenderer();
            if (headerRenderer != null) {
                java.awt.Component comp = headerRenderer
                    .getTableCellRendererComponent(table,
                        columnModel.getColumn(column).getHeaderValue(),
                        false, false, 0, column);
                width = Math.max(comp.getPreferredSize().width + 25, width);
            }

            // Measure widest data cell
            for (int row = 0; row < table.getRowCount(); row++) {
                javax.swing.table.TableCellRenderer renderer =
                    table.getCellRenderer(row, column);
                java.awt.Component comp =
                    table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 15, width);
            }

            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }

} // end class CategoryFrame
