/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inventorycontrolsystem.view;

import com.mycompany.inventorycontrolsystem.dao.SalesInvoiceDAO;
import com.mycompany.inventorycontrolsystem.db.DAOFactory;
import com.mycompany.inventorycontrolsystem.db.DatabaseConnection;
import com.mycompany.inventorycontrolsystem.model.InvoiceItem;
import com.mycompany.inventorycontrolsystem.model.Product;
import com.mycompany.inventorycontrolsystem.model.SalesInvoice;
import com.mycompany.inventorycontrolsystem.model.User;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;

import com.mycompany.inventorycontrolsystem.dao.ProductDAO;
import com.mycompany.inventorycontrolsystem.dao.SalesInvoiceDAO;
import com.mycompany.inventorycontrolsystem.dao.impl.ProductDAOImpl;
import com.mycompany.inventorycontrolsystem.dao.impl.SalesInvoiceDAOImpl;
import com.mycompany.inventorycontrolsystem.db.DatabaseConnection;
import com.mycompany.inventorycontrolsystem.model.InvoiceItem;
import com.mycompany.inventorycontrolsystem.model.Product;
import com.mycompany.inventorycontrolsystem.model.SalesInvoice;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author mgpde
 */
public class POSPanel extends javax.swing.JPanel {

        private final ProductDAO productDAO;
    private final SalesInvoiceDAO salesInvoiceDAO;
    private DefaultTableModel cartTableModel;
    private final List<CartItem> cartItems = new ArrayList<>();
    private javax.swing.JLabel lblInvoiceNumber;
    
    /**
     * Creates new form POSPanel
     */
    public POSPanel() {
        initComponents();
        this.productDAO = new ProductDAOImpl();
        this.salesInvoiceDAO = new SalesInvoiceDAOImpl();

        loadNextInvoiceNumber(); // Safe now, DAO is fully initialized!
        this.cartTableModel = (DefaultTableModel) cartTable.getModel();
        initializeCartTable();
        wireEventListeners();
        initializeDefaults();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBarcodeOrId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        spnQuantity = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        lblNetTotal = new javax.swing.JLabel();
        txtCashPaid = new javax.swing.JTextField();
        lblBalance = new javax.swing.JLabel();
        btnPrintInvoice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1420, 32767));
        setMinimumSize(new java.awt.Dimension(1420, 0));
        setPreferredSize(new java.awt.Dimension(1420, 886));

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel3.setText("Barcode / ID:");

        txtBarcodeOrId.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel4.setText("Qty:");

        btnAddItem.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnAddItem.setText("Add");

        spnQuantity.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        spnQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnQuantity.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addComponent(txtBarcodeOrId, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addGap(55, 55, 55)
                .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtBarcodeOrId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(56, 56, 56))
        );

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 1, 36)); // NOI18N
        jLabel5.setText("INVENTORY CONTROL SYSTEM");

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jLabel1.setText("Welcome, Admin");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        centerPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 1636));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 1636));
        jPanel1.setPreferredSize(new java.awt.Dimension(1145, 1636));

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jLabel2.setText("BILLING SUMMARY");

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel6.setText("GRAND TOTAL :");

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel8.setText("Discount    :");

        jLabel9.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel9.setText("Net Total   :");

        jLabel10.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel10.setText("Cash Paid   :");

        jLabel11.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel11.setText("Balance     :");

        lblGrandTotal.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N

        txtDiscount.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N

        lblNetTotal.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N

        txtCashPaid.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N

        lblBalance.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N

        btnPrintInvoice.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        btnPrintInvoice.setText("Print");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(351, 351, 351)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(584, 584, 584)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel2))
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNetTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtCashPaid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btnPrintInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGrandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNetTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCashPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnPrintInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Code", "Product Name", "Unit Price", "Qty", "Total", "Action"
            }
        ));
        jScrollPane1.setViewportView(cartTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // INNER CLASS: CartItem
    
    /** Simple cart item representation for in-memory tracking */
    private static class CartItem {
        final int productId;
        final String productCode;
        final String productName;
        final BigDecimal unitPrice;
        int quantity;
        BigDecimal lineTotal;
        
        CartItem(int productId, String productCode, String productName, 
                 BigDecimal unitPrice, int quantity) {
            this.productId = productId;
            this.productCode = productCode;
            this.productName = productName;
            this.unitPrice = unitPrice;
            this.quantity = quantity;
            this.lineTotal = unitPrice.multiply(BigDecimal.valueOf(quantity));
        }
        
        void addQuantity(int qty) {
            this.quantity += qty;
            this.lineTotal = unitPrice.multiply(BigDecimal.valueOf(quantity));
        }
    }
    // INITIALIZATION METHODS
    
    private void initializeCartTable() {
        // Clear default rows and set proper column identifiers
        cartTableModel.setRowCount(0);
        cartTableModel.setColumnIdentifiers(new String[]{"Product Code", "Product Name", "Unit Price", "Qty", "Total", "Action"});
        
        // Make table non-editable
        cartTableModel = new DefaultTableModel(
            new String[]{"Product Code", "Product Name", "Unit Price", "Qty", "Total", "Action"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        cartTable.setModel(cartTableModel);
        
        // Re-wrap table in jScrollPane1 to ensure proper JScrollPane configuration
        jScrollPane1.setViewportView(cartTable);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jScrollPane1.setViewportBorder(null);
        
        // Style table header for high contrast visibility using custom renderer to override Look & Feel
        cartTable.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                javax.swing.JLabel label = (javax.swing.JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                label.setBackground(new java.awt.Color(24, 35, 54)); // Dark Blue
                label.setForeground(new java.awt.Color(255, 255, 255)); // White text
                label.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
                label.setHorizontalAlignment(javax.swing.JLabel.CENTER);
                label.setOpaque(true);
                return label;
            }
        });
        cartTable.getTableHeader().repaint();
        
        // Force layout refresh
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
        cartTable.getTableHeader().repaint();
        
        // Add double-click listener for row deletion
        cartTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int row = cartTable.rowAtPoint(e.getPoint());
                    if (row >= 0) {
                        removeCartItem(row);
                    }
                }
            }
        });
    }
    
    private void initializeDefaults() {
        txtDiscount.setText("0.00");
        txtCashPaid.setText("");
        lblGrandTotal.setText("0.00");
        lblNetTotal.setText("0.00");
        lblBalance.setText("0.00");
        spnQuantity.setValue(1);
    }
    
    private void wireEventListeners() {
        // Add item button
        btnAddItem.addActionListener(e -> addNewItem());
        
        // Enter key on barcode field
        txtBarcodeOrId.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    addNewItem();
                }
            }
        });
        
        // Document listeners for real-time calculations
        txtDiscount.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { calculateInvoiceTotals(); }
            @Override
            public void removeUpdate(DocumentEvent e) { calculateInvoiceTotals(); }
            @Override
            public void changedUpdate(DocumentEvent e) { calculateInvoiceTotals(); }
        });
        
        txtCashPaid.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { calculateInvoiceTotals(); }
            @Override
            public void removeUpdate(DocumentEvent e) { calculateInvoiceTotals(); }
            @Override
            public void changedUpdate(DocumentEvent e) { calculateInvoiceTotals(); }
        });
        
        // Print invoice button
        btnPrintInvoice.addActionListener(e -> onPrintInvoice());
    }
    // CART INPUT ENGINE

    /**
     * Normalises raw cashier input to a canonical product code.
     *
     * Rules:
     *  - Strip surrounding whitespace.
     *  - If the value is purely numeric (e.g. "0005"), prepend "PROD-" so it
     *    becomes "PROD-0005" before hitting the DB.
     *  - If it already starts with "PROD-" (case-insensitive), leave it
     *    exactly as-is (preserve the original case the DB uses).
     *  - Any other format (barcode, custom code) is returned unchanged.
     *
     * @param raw  the text the cashier typed
     * @return     the normalised product code / barcode string
     */
    private static String normaliseInput(String raw) {
        if (raw == null) return "";
        String trimmed = raw.trim();
        // Pure digits → treat as zero-padded product code suffix
        if (trimmed.matches("\\d+")) {
            return "PROD-" + trimmed;
        }
        return trimmed;
    }

    private void addNewItem() {
        String rawInput = txtBarcodeOrId.getText().trim();
        if (rawInput.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter a barcode or product ID.",
                "Input Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int quantity = (Integer) spnQuantity.getValue();
        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this,
                "Quantity must be at least 1.",
                "Invalid Quantity", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String normalisedInput = normaliseInput(rawInput);

        // Update the field so the cashier can see what was resolved
        if (!normalisedInput.equals(rawInput)) {
            txtBarcodeOrId.setText(normalisedInput);
        }
        // findById and findByCode already filter is_active=1 at the SQL
        // level.  If a deactivated product is scanned, these return empty.
        Optional<Product> productOpt;
        try {
            if (normalisedInput.matches("\\d+")) {
                // Still numeric after normalise — shouldn't happen, but handle it
                productOpt = productDAO.findById(Integer.parseInt(normalisedInput));
            } else {
                // Try by product code (covers "PROD-0005" and any custom code)
                productOpt = productDAO.findByCode(normalisedInput);

                if (productOpt.isEmpty()) {
                    // Fall back to barcode field scan (findAll only returns active)
                    productOpt = productDAO.findAll().stream()
                        .filter(p -> normalisedInput.equalsIgnoreCase(p.getBarcode()))
                        .findFirst();
                }
            }
        } catch (Exception ex) {
            System.out.println("Error fetching product for input '{}'");
            JOptionPane.showMessageDialog(this,
                "Error fetching product: " + ex.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // findByCode and findById filter is_active=1 at the SQL level, so an
        // empty result means the product either doesn't exist or is deactivated.
        // One message covers both cases correctly for the cashier.
        if (productOpt.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Product not found: \"" + normalisedInput + "\"\n\n"
                + "This product either does not exist or has been deactivated\n"
                + "and cannot be sold.",
                "Product Unavailable", JOptionPane.WARNING_MESSAGE);
            txtBarcodeOrId.setText("");
            txtBarcodeOrId.requestFocus();
            return;
        }

        Product product = productOpt.get();
        // findByCode/findById already enforce is_active=1 at SQL level.
        // This check catches any edge-case where a cached or stale object
        // with is_active=false slips through (e.g. product deactivated mid-session).
        if (!product.isActive()) {
            JOptionPane.showMessageDialog(this,
                "This product has been deactivated and cannot be sold.",
                "Product Unavailable", JOptionPane.WARNING_MESSAGE);
            txtBarcodeOrId.setText("");
            txtBarcodeOrId.requestFocus();
            return;
        }
        if (product.getQuantityOnHand() <= 0) {
            JOptionPane.showMessageDialog(this,
                "\"" + product.getProductName() + "\" is out of stock.\n"
                + "Available quantity: 0",
                "Out of Stock", JOptionPane.WARNING_MESSAGE);
            txtBarcodeOrId.setText("");
            txtBarcodeOrId.requestFocus();
            return;
        }
        if (product.getQuantityOnHand() < quantity) {
            JOptionPane.showMessageDialog(this,
                String.format("Insufficient stock for \"%s\".\nAvailable: %d  |  Requested: %d",
                    product.getProductName(),
                    product.getQuantityOnHand(),
                    quantity),
                "Stock Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Optional<CartItem> existing = cartItems.stream()
            .filter(item -> item.productId == product.getProductId())
            .findFirst();

        if (existing.isPresent()) {
            CartItem cartItem = existing.get();
            int newQty = cartItem.quantity + quantity;
            if (newQty > product.getQuantityOnHand()) {
                JOptionPane.showMessageDialog(this,
                    String.format("Cannot add %d more of \"%s\".\n"
                        + "Already in cart: %d  |  Available: %d",
                        quantity, product.getProductName(),
                        cartItem.quantity, product.getQuantityOnHand()),
                    "Stock Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            cartItem.addQuantity(quantity);
        } else {
            cartItems.add(new CartItem(
                product.getProductId(),
                product.getProductCode(),
                product.getProductName(),
                product.getSellingPrice(),
                quantity
            ));
        }

        refreshCartTable();
        txtBarcodeOrId.setText("");
        spnQuantity.setValue(1);
        txtBarcodeOrId.requestFocus();
    }
    
    private void removeCartItem(int row) {
        if (row >= 0 && row < cartItems.size()) {
            cartItems.remove(row);
            refreshCartTable();
        }
    }
    
    private void refreshCartTable() {
        cartTableModel.setRowCount(0);
        for (CartItem item : cartItems) {
            cartTableModel.addRow(new Object[]{
                item.productCode,
                item.productName,
                String.format("%.2f", item.unitPrice),
                item.quantity,
                String.format("%.2f", item.lineTotal),
                "Double-click to remove"
            });
        }
        calculateInvoiceTotals();
    }
    // REAL-TIME CALCULATION ENGINE
    
    private void calculateInvoiceTotals() {
        // Calculate grand total
        BigDecimal grandTotal = cartItems.stream()
            .map(item -> item.lineTotal)
            .reduce(BigDecimal.ZERO, BigDecimal::add);
        
        lblGrandTotal.setText(String.format("%.2f", grandTotal));
        
        // Parse discount with fallback to 0.00
        BigDecimal discount = parseDecimal(txtDiscount.getText(), BigDecimal.ZERO);
        
        // Calculate net total
        BigDecimal netTotal = grandTotal.subtract(discount);
        if (netTotal.compareTo(BigDecimal.ZERO) < 0) {
            netTotal = BigDecimal.ZERO;
        }
        lblNetTotal.setText(String.format("%.2f", netTotal));
        
        // Parse cash paid with fallback to 0.00
        BigDecimal cashPaid = parseDecimal(txtCashPaid.getText(), BigDecimal.ZERO);
        
        // Calculate balance
        BigDecimal balance = cashPaid.subtract(netTotal);
        lblBalance.setText(String.format("%.2f", balance));
    }
    
    private BigDecimal parseDecimal(String text, BigDecimal fallback) {
        try {
            if (text == null || text.trim().isEmpty()) {
                return fallback;
            }
            return new BigDecimal(text.trim());
        } catch (NumberFormatException ex) {
            return fallback;
        }
    }
    // TRANSACTION FINALIZATION
    
    private void onPrintInvoice() {
        if (cartItems.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cart is empty. Add items before printing invoice.", 
                "Empty Cart", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        BigDecimal netTotal = new BigDecimal(lblNetTotal.getText());
        BigDecimal cashPaid = parseDecimal(txtCashPaid.getText(), BigDecimal.ZERO);
        
        if (cashPaid.compareTo(netTotal) < 0) {
            JOptionPane.showMessageDialog(this, 
                String.format("Insufficient payment!\nNet Total: %.2f\nCash Paid: %.2f", netTotal, cashPaid), 
                "Payment Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Confirm transaction
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Confirm transaction?\n\nTotal: " + lblNetTotal.getText() + "\nPaid: " + txtCashPaid.getText(), 
            "Confirm Transaction", JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        // Execute transaction
        Connection conn = null;
        try {
            conn = DatabaseConnection.getInstance().getConnection();
            conn.setAutoCommit(false);
            
            // Create sales invoice
            SalesInvoice invoice = new SalesInvoice();
            invoice.setUserId(1); // TODO: Get current user ID
            invoice.setInvoiceNumber(salesInvoiceDAO.generateInvoiceNumber());
            invoice.setInvoiceDate(java.time.LocalDateTime.now());
            invoice.setSubtotal(new BigDecimal(lblGrandTotal.getText()));
            invoice.setDiscountAmount(parseDecimal(txtDiscount.getText(), BigDecimal.ZERO));
            invoice.setTotalAmount(netTotal);
            invoice.setAmountPaid(cashPaid);
            invoice.setChangeAmount(cashPaid.subtract(netTotal));
            invoice.setPaymentMethod("CASH");
            invoice.setStatus("PAID");
            
            // Add invoice items
            for (CartItem item : cartItems) {
                InvoiceItem invItem = new InvoiceItem();
                invItem.setProductId(item.productId);
                invItem.setProductCode(item.productCode);
                invItem.setProductName(item.productName);
                invItem.setQuantity(item.quantity);
                invItem.setUnitPrice(item.unitPrice);
                invItem.setTaxRate(BigDecimal.ZERO); // TODO: Get from product if needed
                invItem.recalculate();
                invoice.addItem(invItem);
            }
            
            // Insert invoice with items using the shared connection (this also updates stock)
            int invoiceId = salesInvoiceDAO.insertWithItems(invoice, conn);
            
            // Commit immediately to guarantee data persistence
            conn.commit();
            loadNextInvoiceNumber();
            
            JOptionPane.showMessageDialog(this, 
                "Transaction completed successfully!\nInvoice ID: " + invoiceId, 
                "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // Clear cart and reset fields
            cartItems.clear();
            refreshCartTable();
            initializeDefaults();
            
        } catch (SQLException ex) {
            try {
                if (conn != null && !conn.getAutoCommit()) {
                    conn.rollback();
                }
            } catch (SQLException rollbackEx) {
                rollbackEx.printStackTrace();
            }
            System.out.println("Transaction failed");
            JOptionPane.showMessageDialog(this, 
                "Transaction failed: " + ex.getMessage(), 
                "Transaction Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Always reset auto-commit to true to restore default state
            if (conn != null) {
                try {
                    conn.setAutoCommit(true);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnPrintInvoice;
    private javax.swing.JTable cartTable;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblNetTotal;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextField txtBarcodeOrId;
    private javax.swing.JTextField txtCashPaid;
    private javax.swing.JTextField txtDiscount;
    // End of variables declaration//GEN-END:variables

    private void loadNextInvoiceNumber() {
        try {
            int lastId = salesInvoiceDAO.getLastInvoiceId();
            int nextId = lastId + 1;
            jLabel1.setText("Welcome, Admin | Next Invoice ID: " + nextId);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
