/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inventorycontrolsystem.view;

import com.mycompany.inventorycontrolsystem.controller.ProductController;
import com.mycompany.inventorycontrolsystem.db.DAOFactory;
import com.mycompany.inventorycontrolsystem.model.Category;
import com.mycompany.inventorycontrolsystem.model.Product;
import com.mycompany.inventorycontrolsystem.model.Supplier;
import com.mycompany.inventorycontrolsystem.model.User;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFColor;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.*;
import java.io.FileOutputStream;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;

/**
 * Product Management screen.
 * NetBeans JPanel Form — GUI Builder designed.
 * Business logic is wired below the locked initComponents() block.
 */
public class ProductFrame extends javax.swing.JPanel {
        private final ProductController controller = new ProductController();
    private final User currentUser;
    private Product editingProduct = null;
    private DefaultTableModel liveTableModel;

    // Reference to PurchaseOrderPanel so we can refresh its product combo
    // immediately after a new product is saved.
    private PurchaseOrderPanel purchaseOrderPanel;

    /**
     * Called by DashboardFrame when the user clicks "Products" in the sidebar.
     *
     * @param user the authenticated session user
     * @param purchaseOrderPanel reference used to refresh the product combo on save
     */
    public ProductFrame(User user, PurchaseOrderPanel purchaseOrderPanel) {
        this.currentUser = user;
        this.purchaseOrderPanel = purchaseOrderPanel;
        initComponents();          // NetBeans locked block — do not touch
        setupData();             // wire up all backend logic after GUI is built
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCurrentUser = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        txtCostPrice = new javax.swing.JTextField();
        txtReorderLevel = new javax.swing.JTextField();
        txtSellingPrice = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lblBarcodePreview = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        radioActive = new javax.swing.JRadioButton();
        radioInactive = new javax.swing.JRadioButton();
        btnDeactivate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExportPDF = new javax.swing.JButton();
        btnExportExcel = new javax.swing.JButton();

        setBackground(new java.awt.Color(15, 23, 42));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 36)); // NOI18N
        jLabel1.setText("Product Management");

        lblCurrentUser.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        lblCurrentUser.setText("User :");
        lblCurrentUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCurrentUserActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        txtSearch.setText("Search :");

        btnSearch.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnSearch.setText("Search");

        btnRefresh.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnRefresh.setText("Refresh");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnSearch)
                .addGap(54, 54, 54)
                .addComponent(btnRefresh)
                .addGap(0, 534, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnRefresh))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        productTable.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        productTable.setForeground(new java.awt.Color(0, 0, 0));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Category", "Price", "Stock"
            }
        ));
        jScrollPane1.setViewportView(productTable);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel2.setText("Product Details");

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel3.setText("Product Code:");

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel4.setText("Product Name:");

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel5.setText("Category:");

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel6.setText("Cost Price:");

        jLabel7.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel7.setText("Selling Price:");

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel8.setText("Re-order Level:");

        txtName.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        txtCode.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        txtCostPrice.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        txtReorderLevel.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        txtSellingPrice.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        cmbCategory.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel9.setText("Barcode Preview");

        lblBarcodePreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel11.setText("Status :");

        buttonGroup1.add(radioActive);
        radioActive.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        radioActive.setText("Active");

        buttonGroup1.add(radioInactive);
        radioInactive.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        radioInactive.setText("Inactive");

        btnDeactivate.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnDeactivate.setText("Deactivate");

        btnSave.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnSave.setText("Save");

        btnClear.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnClear.setText("Clear");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(140, 140, 140)
                        .addComponent(radioActive)
                        .addGap(72, 72, 72)
                        .addComponent(radioInactive)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear)
                                .addGap(86, 86, 86)
                                .addComponent(btnDeactivate)
                                .addGap(29, 29, 29))
                            .addComponent(lblBarcodePreview, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCostPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReorderLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSellingPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(89, 89, 89))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtReorderLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBarcodePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(radioActive)
                    .addComponent(radioInactive))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeactivate)
                    .addComponent(btnSave)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExportPDF.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnExportPDF.setText("Export PDF Report");

        btnExportExcel.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnExportExcel.setText("Export to Excel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnExportExcel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExportPDF)
                        .addGap(65, 65, 65)))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExportPDF)
                            .addComponent(btnExportExcel))
                        .addGap(36, 36, 36))))
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCurrentUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCurrentUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCurrentUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBarcodePreview;
    private javax.swing.JTextField lblCurrentUser;
    private javax.swing.JTable productTable;
    private javax.swing.JRadioButton radioActive;
    private javax.swing.JRadioButton radioInactive;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCostPrice;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtReorderLevel;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSellingPrice;
    // End of variables declaration//GEN-END:variables
    // BACKEND INITIALISATION
    // Called once from the constructor after initComponents().

    /**
     * Wires up everything that initComponents() cannot do:
     * - replaces the static table model with a live DefaultTableModel
     * - populates cmbCategory from the database
     * - sets lblCurrentUser to the logged-in user's name
     * - attaches all ActionListeners
     * - loads the initial product list asynchronously
     */
    private void setupData() {
        lblCurrentUser.setText("User:  " + currentUser.getFullName()
                + "  [" + getRoleName(currentUser.getRoleId()) + "]");
        lblCurrentUser.setEditable(false);
        lblCurrentUser.setBorder(null);
        //    Columns match the design-time headers exactly.
        //    Column 5 (ID) is hidden — it stores the product_id for lookups.
        liveTableModel = new DefaultTableModel(
                new String[]{"Code", "Name", "Category", "Price (RM)", "Stock", "ID"}, 0) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
            @Override
            public Class<?> getColumnClass(int col) {
                return (col == 3 || col == 4 || col == 5) ? Integer.class : String.class;
            }
        };
        productTable.setModel(liveTableModel);

        // Hide the ID column — it exists for data but must not show
        productTable.getColumnModel().getColumn(5).setMinWidth(0);
        productTable.getColumnModel().getColumn(5).setMaxWidth(0);
        productTable.getColumnModel().getColumn(5).setWidth(0);

        // Style the table header
        productTable.getTableHeader().setUI(
                new javax.swing.plaf.basic.BasicTableHeaderUI());
        productTable.getTableHeader().setFont(
                new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        productTable.getTableHeader().setBackground(new java.awt.Color(34, 45, 65));
        productTable.getTableHeader().setForeground(java.awt.Color.WHITE);
        productTable.getTableHeader().setReorderingAllowed(false);
        productTable.setRowHeight(28);
        productTable.setSelectionBackground(new java.awt.Color(41, 98, 178));
        productTable.setSelectionForeground(java.awt.Color.WHITE);
        productTable.setGridColor(new java.awt.Color(218, 224, 235));
        populateCategoryCombo();
        radioActive.setSelected(true);
        lblBarcodePreview.setHorizontalAlignment(SwingConstants.CENTER);
        lblBarcodePreview.setForeground(new java.awt.Color(127, 140, 141));
        lblBarcodePreview.setFont(new java.awt.Font("JetBrains Mono", java.awt.Font.PLAIN, 11));
        lblBarcodePreview.setText("Barcode preview appears here");
        btnSearch.addActionListener(e -> onSearchClicked());
        btnRefresh.addActionListener(e -> loadProductsAsync(null));
        btnSave.addActionListener(e -> onSaveClicked());
        btnClear.addActionListener(e -> clearForm());
        btnDeactivate.addActionListener(e -> onDeactivateClicked());
        btnExportPDF.addActionListener(e -> onExportPDF());
        btnExportExcel.addActionListener(e -> onExportExcel());

        // Enter key in search field triggers search
        txtSearch.addActionListener(e -> onSearchClicked());

        // Clear placeholder text when user clicks into the search field
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            private static final String PLACEHOLDER = "Search :";
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtSearch.getText().trim().equalsIgnoreCase(PLACEHOLDER)) {
                    txtSearch.setText("");
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtSearch.getText().trim().isEmpty()) {
                    txtSearch.setText(PLACEHOLDER);
                }
            }
        });

        // Row click → populate form fields
        productTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) onRowSelected();
        });

        // Live barcode preview: trigger when txtCode is set programmatically
        // (via loadNextProductCode or onRowSelected) by listening for text changes
        txtCode.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            private void refresh() {
                String code = txtCode.getText().trim();
                if (!code.isEmpty() && !code.equals("Generating...")) {
                    controller.renderBarcodeOnLabel(lblBarcodePreview, code);
                }
            }
            @Override public void insertUpdate (javax.swing.event.DocumentEvent e) { refresh(); }
            @Override public void removeUpdate (javax.swing.event.DocumentEvent e) { refresh(); }
            @Override public void changedUpdate(javax.swing.event.DocumentEvent e) { refresh(); }
        });
        loadProductsAsync(null);
        // txtCode is locked non-editable permanently for new entries.
        // When the user selects an existing row, onRowSelected() re-populates
        // it with the stored code (also non-editable — the PK never changes).
        txtCode.setEditable(false);
        loadNextProductCode();
    }
    // DATA LOADING — SwingWorker

    /**
     * Loads products into the table on a background thread.
     * Passing {@code null} loads all products; passing a keyword performs search.
     *
     * @param keyword search term, or {@code null} to load all
     */
    private void loadProductsAsync(String keyword) {
        // Show a loading indicator in the table header area
        btnRefresh.setEnabled(false);
        btnSearch.setEnabled(false);

        new SwingWorker<List<Product>, Void>() {

            @Override
            protected List<Product> doInBackground() {
                return (keyword == null || keyword.isBlank())
                        ? controller.getAllProducts()
                        : controller.searchProducts(keyword);
            }

            @Override
            protected void done() {
                try {
                    List<Product> products = get();
                    liveTableModel.setRowCount(0);          // clear existing rows

                    for (Product p : products) {
                        liveTableModel.addRow(new Object[]{
                            p.getProductCode(),
                            p.getProductName(),
                            p.getCategoryName() != null ? p.getCategoryName() : "—",
                            String.format("%.2f", p.getSellingPrice()),
                            p.getQuantityOnHand(),
                            p.getProductId()                // hidden ID column
                        });
                    }

                    // Auto-resize columns after data is populated
                    autoResizeColumns(productTable);

                } catch (ExecutionException ex) {
                    ex.getCause().printStackTrace();
                    JOptionPane.showMessageDialog(
                            ProductFrame.this,
                            "Could not load products.\nCheck database connection.",
                            "Load Error", JOptionPane.ERROR_MESSAGE);
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                } finally {
                    btnRefresh.setEnabled(true);
                    btnSearch.setEnabled(true);
                }
            }
        }.execute();
    }
    // COMBO BOX POPULATION

    /**
     * Fills cmbCategory with active category names from the database.
     * Stores the category name as the display string.
     * The parallel {@code categoryList} field is used to resolve the
     * selected name back to a category_id on save.
     */
    private List<Category> categoryList;

    private void populateCategoryCombo() {
        try {
            categoryList = DAOFactory.getCategoryDAO().findActive();
            cmbCategory.removeAllItems();
            cmbCategory.addItem("-- Select Category --");
            for (Category c : categoryList) {
                cmbCategory.addItem(c.getCategoryName());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Could not load categories from database.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
    // EVENT HANDLERS

    /** Triggered when Search button is clicked (or Enter pressed in txtSearch). */
    private void onSearchClicked() {
        String keyword = txtSearch.getText().trim();
        // Ignore if the field still contains the design-time placeholder text
        if (keyword.isEmpty()
                || keyword.equalsIgnoreCase("Search :")
                || keyword.equalsIgnoreCase("Search")) {
            loadProductsAsync(null);
        } else {
            loadProductsAsync(keyword);
        }
    }

    /**
     * Triggered when a row is selected in productTable.
     * Reads the hidden ID column and loads that product's full record
     * into all form fields.
     */
    private void onRowSelected() {
        int row = productTable.getSelectedRow();
        if (row < 0) return;

        int productId = (int) liveTableModel.getValueAt(row, 5);

        controller.getById(productId).ifPresent(p -> {
            editingProduct = p;

            txtCode.setText(p.getProductCode());
            txtName.setText(p.getProductName());
            txtCostPrice.setText(
                    p.getCostPrice() != null ? p.getCostPrice().toPlainString() : "0.00");
            txtSellingPrice.setText(
                    p.getSellingPrice() != null ? p.getSellingPrice().toPlainString() : "0.00");
            txtReorderLevel.setText(String.valueOf(p.getReorderLevel()));

            // Match category combo to this product's category
            cmbCategory.setSelectedIndex(0);    // default = "-- Select Category --"
            if (categoryList != null) {
                for (int i = 0; i < categoryList.size(); i++) {
                    if (categoryList.get(i).getCategoryId() == p.getCategoryId()) {
                        cmbCategory.setSelectedIndex(i + 1); // +1 for the placeholder item
                        break;
                    }
                }
            }

            // Status radio buttons
            if (p.isActive()) {
                radioActive.setSelected(true);
            } else {
                radioInactive.setSelected(true);
            }

            // Live barcode preview
            String barcode = p.getBarcode() != null ? p.getBarcode() : p.getProductCode();
            if (!barcode.isBlank()) {
                controller.renderBarcodeOnLabel(lblBarcodePreview, barcode);
            }

            System.out.println("Row selected → loaded product ID={}");
        });
    }

    /** Triggered by the Save button. Validates fields, then inserts or updates. */
    private void onSaveClicked() {
        String code = txtCode.getText().trim();
        String name = txtName.getText().trim();

        if (code.isEmpty()) {
            showError("Product Code is required.");
            txtCode.requestFocusInWindow();
            return;
        }
        if (name.isEmpty()) {
            showError("Product Name is required.");
            txtName.requestFocusInWindow();
            return;
        }
        if (cmbCategory.getSelectedIndex() == 0) {
            showError("Please select a Category.");
            cmbCategory.requestFocusInWindow();
            return;
        }

        BigDecimal costPrice, sellingPrice;
        int reorderLevel;
        try {
            costPrice    = new BigDecimal(txtCostPrice.getText().trim());
            sellingPrice = new BigDecimal(txtSellingPrice.getText().trim());
            reorderLevel = Integer.parseInt(
                    txtReorderLevel.getText().trim().isEmpty()
                    ? "10" : txtReorderLevel.getText().trim());
        } catch (NumberFormatException ex) {
            showError("Cost Price, Selling Price, and Reorder Level must be valid numbers.");
            return;
        }
        Product p = (editingProduct != null) ? editingProduct : new Product();
        p.setProductCode  (code);
        p.setProductName  (name);
        p.setCostPrice    (costPrice);
        p.setSellingPrice (sellingPrice);
        p.setTaxRate      (java.math.BigDecimal.ZERO);   // default 0% — no tax field in this form
        p.setReorderLevel (reorderLevel);
        p.setBarcode      (code);                        // use product code as barcode
        p.setDescription  ("");                          // empty string — never null
        p.setImagePath    (null);                        // nullable column — safe
        p.setActive       (radioActive.isSelected());
        p.setUnit         ("pcs");                       // default unit

        // Resolve category name → category_id
        int catIndex = cmbCategory.getSelectedIndex() - 1; // -1 for placeholder
        if (catIndex >= 0 && categoryList != null && catIndex < categoryList.size()) {
            p.setCategoryId(categoryList.get(catIndex).getCategoryId());
        }
        try {
            boolean success;
            if (editingProduct == null) {
                success = controller.addProduct(p) > 0;
            } else {
                success = controller.updateProduct(p);
            }

            if (success) {
                JOptionPane.showMessageDialog(this,
                        "Product saved successfully.",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadProductsAsync(null);

                // Refresh the product dropdown in Purchase Order panel immediately
                if (purchaseOrderPanel != null) {
                    purchaseOrderPanel.refreshProductCombo();
                }
            } else {
                showError("Save failed.\n\n"
                        + "Possible causes:\n"
                        + "  • Product code already exists in the database\n"
                        + "  • A required field is missing or invalid\n\n"
                        + "Check the NetBeans Output window for the full SQL error.");
            }
        } catch (IllegalArgumentException ex) {
            showError(ex.getMessage());
        } catch (Exception ex) {
            // Catch-all so any unexpected runtime exception shows the real message
            ex.printStackTrace(); // prints full stack trace to NetBeans Output tab
            showError("Unexpected error during save:\n" + ex.getMessage());
        }
    }

    /** Triggered by the Deactivate button — soft-deletes the selected product. */
    private void onDeactivateClicked() {
        int row = productTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select a product from the table first.",
                    "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String productName = liveTableModel.getValueAt(row, 1).toString();
        int productId      = (int) liveTableModel.getValueAt(row, 5);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Deactivate product:\n\"" + productName + "\"?\n\n"
                + "The product will be hidden but its history is preserved.",
                "Confirm Deactivate",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean ok = controller.deactivateProduct(productId);
            if (ok) {
                clearForm();
                loadProductsAsync(null);
            } else {
            }
        }
    }

    /** Exports the product list to a real PDF file using Apache PDFBox. */
    private void onExportPDF() {
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Save PDF Report");
        fc.setSelectedFile(new java.io.File("Products_Report.pdf"));
        fc.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "PDF Files (*.pdf)", "pdf"));
        if (fc.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) return;

        String path = fc.getSelectedFile().getAbsolutePath();
        if (!path.toLowerCase().endsWith(".pdf")) path += ".pdf";

        // Snapshot the visible columns (skip hidden ID column 5) on the EDT
        final int rowCount = liveTableModel.getRowCount();
        final java.util.List<Object[]> snapshot = new java.util.ArrayList<>(rowCount);
        for (int r = 0; r < rowCount; r++) {
            snapshot.add(new Object[]{
                liveTableModel.getValueAt(r, 0),  // Code
                liveTableModel.getValueAt(r, 1),  // Name
                liveTableModel.getValueAt(r, 2),  // Category
                liveTableModel.getValueAt(r, 3),  // Price (RM)
                liveTableModel.getValueAt(r, 4)   // Stock
            });
        }
        final String generatedBy = currentUser.getFullName();
        final String finalPath   = path;

        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                String[] headers = {"Product Code", "Product Name",
                                    "Category", "Price (RM)", "Stock Qty"};
                com.mycompany.inventorycontrolsystem.util.PdfExportUtil.exportTable(
                        "Product Catalogue Report",
                        headers,
                        snapshot,
                        finalPath,
                        generatedBy);
                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                    JOptionPane.showMessageDialog(ProductFrame.this,
                        "PDF exported successfully!\nSaved to:\n" + finalPath,
                        "Export Complete", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(ProductFrame.this,
                        "PDF export failed:\n" + ex.getMessage(),
                        "Export Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();
    }

    /** Exports the product list directly to Excel (.xlsx) using Apache POI. */
    private void onExportExcel() {
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Save Excel Report");
        fc.setSelectedFile(new java.io.File("Products_Report.xlsx"));
        fc.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Excel Files (*.xlsx)", "xlsx"));
        if (fc.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) return;

        String path = fc.getSelectedFile().getAbsolutePath();
        if (!path.toLowerCase().endsWith(".xlsx")) path += ".xlsx";

        // Snapshot the table data on the EDT before handing off to the worker
        final int rowCount = liveTableModel.getRowCount();
        final Object[][] snapshot = new Object[rowCount][5];
        for (int r = 0; r < rowCount; r++) {
            for (int c = 0; c < 5; c++) {
                snapshot[r][c] = liveTableModel.getValueAt(r, c);
            }
        }
        final String generatedBy = currentUser.getFullName();
        final String finalPath   = path;

        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                try (XSSFWorkbook workbook = new XSSFWorkbook()) {

                    Sheet sheet = workbook.createSheet("Products");
                    CellStyle headerStyle = workbook.createCellStyle();
                    org.apache.poi.ss.usermodel.Font headerFont = workbook.createFont();
                    headerFont.setBold(true);
                    headerFont.setColor(IndexedColors.WHITE.getIndex());
                    headerFont.setFontHeightInPoints((short) 11);
                    headerStyle.setFont(headerFont);
                    headerStyle.setFillForegroundColor(
                        new XSSFColor(new byte[]{(byte) 34, (byte) 45, (byte) 65}, null));
                    headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
                    headerStyle.setBorderBottom(BorderStyle.MEDIUM);
                    headerStyle.setAlignment(HorizontalAlignment.LEFT);
                    CellStyle altStyle = workbook.createCellStyle();
                    altStyle.setFillForegroundColor(
                        new XSSFColor(new byte[]{(byte) 245, (byte) 247, (byte) 250}, null));
                    altStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
                    Row titleRow = sheet.createRow(0);
                    titleRow.setHeightInPoints(22);
                    Cell titleCell = titleRow.createCell(0);
                    titleCell.setCellValue("INVENTORY CONTROL SYSTEM — Product Catalogue Report");
                    CellStyle titleStyle = workbook.createCellStyle();
                    org.apache.poi.ss.usermodel.Font titleFont = workbook.createFont();
                    titleFont.setBold(true);
                    titleFont.setFontHeightInPoints((short) 14);
                    titleFont.setColor(IndexedColors.DARK_BLUE.getIndex());
                    titleStyle.setFont(titleFont);
                    titleCell.setCellStyle(titleStyle);
                    sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, 4));
                    Row subRow = sheet.createRow(1);
                    subRow.createCell(0).setCellValue(
                        "Generated by: " + generatedBy + "   |   " + new java.util.Date());
                    sheet.addMergedRegion(new CellRangeAddress(1, 1, 0, 4));

                    sheet.createRow(2); // blank spacer
                    String[] headers = {
                        "Product Code", "Product Name",
                        "Category", "Price (RM)", "Stock Qty"
                    };
                    Row hdrRow = sheet.createRow(3);
                    hdrRow.setHeightInPoints(18);
                    for (int i = 0; i < headers.length; i++) {
                        Cell c = hdrRow.createCell(i);
                        c.setCellValue(headers[i]);
                        c.setCellStyle(headerStyle);
                    }
                    for (int r = 0; r < snapshot.length; r++) {
                        Row dataRow = sheet.createRow(r + 4);
                        for (int c = 0; c < snapshot[r].length; c++) {
                            Cell cell = dataRow.createCell(c);
                            Object val = snapshot[r][c];
                            if (val instanceof Number) {
                                cell.setCellValue(((Number) val).doubleValue());
                            } else {
                                cell.setCellValue(val != null ? val.toString() : "");
                            }
                            if (r % 2 == 1) cell.setCellStyle(altStyle);
                        }
                    }
                    for (int i = 0; i < headers.length; i++) {
                        sheet.autoSizeColumn(i);
                        // Add a little extra padding beyond autoSizeColumn
                        sheet.setColumnWidth(i, sheet.getColumnWidth(i) + 1024);
                    }
                    try (FileOutputStream fos = new FileOutputStream(finalPath)) {
                        workbook.write(fos);
                    }
                }
                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                    JOptionPane.showMessageDialog(ProductFrame.this,
                        "Export Successful!\n\nReport saved to:\n" + finalPath,
                        "Export Complete", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(ProductFrame.this,
                        "Export failed:\n" + ex.getMessage(),
                        "Export Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();
    }
    // FORM HELPERS

    /**
     * Fetches the next PROD-XXXX code from the database on a background thread
     * and applies it to txtCode on the EDT.
     *
     * Called on startup (from setupData) and whenever clearForm() resets
     * the form for a new product entry.  txtCode is locked non-editable so
     * the generated value is the only way a code gets into that field for
     * new records.
     */
    private void loadNextProductCode() {
        // Disable the field while loading so the user can't type in a stale state
        txtCode.setEditable(false);
        txtCode.setEnabled(false);
        txtCode.setText("Generating...");

        new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() {
                return controller.generateNextProductCode();
            }

            @Override
            protected void done() {
                try {
                    String nextCode = get();
                    txtCode.setText(nextCode);
                    // Style it visually so the admin knows it is auto-generated
                    txtCode.setBackground(new java.awt.Color(235, 245, 255));
                    txtCode.setForeground(new java.awt.Color(20, 30, 80));
                    txtCode.setFont(new java.awt.Font("JetBrains Mono", java.awt.Font.BOLD, 14));
                    txtCode.setToolTipText("Auto-generated — format is locked to PROD-XXXX");
                    System.out.println("Next product code generated: {}");
                } catch (ExecutionException ex) {
                    ex.getCause().printStackTrace();
                    txtCode.setText("PROD-0001");   // safe fallback
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                    txtCode.setText("PROD-0001");
                } finally {
                    // Keep non-editable: admin must never free-type a product code
                    txtCode.setEditable(false);
                    txtCode.setEnabled(true);
                }
            }
        }.execute();
    }

    /** Clears all form fields and resets state to "add new product" mode. */
    private void clearForm() {
        editingProduct = null;
        // txtCode is intentionally NOT cleared here — loadNextProductCode()
        // replaces it with the next auto-generated value immediately below.
        txtName.setText("");
        txtCostPrice.setText("0.00");
        txtSellingPrice.setText("0.00");
        txtReorderLevel.setText("10");
        cmbCategory.setSelectedIndex(0);
        radioActive.setSelected(true);
        lblBarcodePreview.setIcon(null);
        lblBarcodePreview.setText("Barcode preview appears here");
        productTable.clearSelection();

        // Regenerate and lock the product code for the next new entry
        loadNextProductCode();

        // Focus moves to the first user-editable field
        txtName.requestFocusInWindow();
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message,
                "Validation Error", JOptionPane.WARNING_MESSAGE);
    }

    /** Returns a human-readable role name from a role ID integer. */
    private String getRoleName(int roleId) {
        return switch (roleId) {
            case 1  -> "Admin";
            case 2  -> "Manager";
            default -> "Cashier";
        };
    }

    /**
     * Resizes every column to fit both its header text and the widest
     * cell value currently in the table.
     * Called from SwingWorker.done() so row data is present when measured.
     *
     * @param table the JTable to auto-size (null-safe)
     */
    private void autoResizeColumns(javax.swing.JTable table) {
        if (table == null) return;
        final javax.swing.table.TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 50; // minimum

            // Measure header
            javax.swing.table.TableCellRenderer headerRenderer =
                table.getTableHeader().getDefaultRenderer();
            if (headerRenderer != null) {
                java.awt.Component comp = headerRenderer
                    .getTableCellRendererComponent(table,
                        columnModel.getColumn(column).getHeaderValue(),
                        false, false, 0, column);
                width = Math.max(comp.getPreferredSize().width + 25, width);
            }

            // Measure widest data cell
            for (int row = 0; row < table.getRowCount(); row++) {
                javax.swing.table.TableCellRenderer renderer =
                    table.getCellRenderer(row, column);
                java.awt.Component comp =
                    table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 15, width);
            }

            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }
}

