/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inventorycontrolsystem.view;

/**
 *
 * @author mgpde
 */
public class PurchaseOrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form PurchaseOrderPanel
     */
    public PurchaseOrderPanel() {
        initComponents();
    }

    public PurchaseOrderPanel(com.mycompany.inventorycontrolsystem.model.User user) {
        initComponents();
        this.currentUser = user;
        setupData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtOrderDate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbProduct = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPOItems = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        btnReceiveStock = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();

        pnlHeader.setBackground(new java.awt.Color(11, 19, 37));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Purchase Order Management");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel2.setText("Supplier");

        cmbSupplier.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel3.setText("Order Date");

        txtOrderDate.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(342, 342, 342)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOrderDate)
                    .addComponent(cmbSupplier, 0, 306, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel4.setText("Product");

        cmbProduct.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        cmbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel5.setText("Quantity");

        txtQty.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel6.setText("Unit Cost");

        txtCost.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N

        btnAddItem.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnAddItem.setText("Add to List");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQty)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(214, 214, 214))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddItem)
                .addGap(575, 575, 575))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblPOItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product", "Qty", "Cost", "Total", "Action"
            }
        ));
        jScrollPane1.setViewportView(tblPOItems);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel7.setText("Grand Total:");

        lblGrandTotal.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        lblGrandTotal.setText("0.00");

        btnReceiveStock.setBackground(new java.awt.Color(0, 51, 204));
        btnReceiveStock.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnReceiveStock.setText("Receive Stock");

        btnClear.setBackground(new java.awt.Color(0, 153, 153));
        btnClear.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnClear.setText("Clear");

        btnPlaceOrder.setBackground(new java.awt.Color(0, 153, 0));
        btnPlaceOrder.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btnPlaceOrder.setText("Place Order");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnPlaceOrder)
                        .addGap(148, 148, 148)
                        .addComponent(btnReceiveStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(212, 212, 212))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblGrandTotal))
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReceiveStock)
                    .addComponent(btnClear)
                    .addComponent(btnPlaceOrder))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        addNewItem();
    }//GEN-LAST:event_btnAddItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnReceiveStock;
    private javax.swing.JComboBox<String> cmbProduct;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTable tblPOItems;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtOrderDate;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
    private static final java.time.format.DateTimeFormatter DATE_FMT =
            java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");    private final com.mycompany.inventorycontrolsystem.dao.SupplierDAO
            supplierDAO = com.mycompany.inventorycontrolsystem.db.DAOFactory.getSupplierDAO();
    private final com.mycompany.inventorycontrolsystem.dao.ProductDAO
            productDAO  = com.mycompany.inventorycontrolsystem.db.DAOFactory.getProductDAO();
    private final com.mycompany.inventorycontrolsystem.dao.PurchaseOrderDAO
            poDAO       = com.mycompany.inventorycontrolsystem.db.DAOFactory.getPurchaseOrderDAO();    private com.mycompany.inventorycontrolsystem.model.User currentUser;

    /** Call this from DashboardFrame after constructing the panel. */
    public void setCurrentUser(
            com.mycompany.inventorycontrolsystem.model.User user) {
        this.currentUser = user;
    }    // GEN declared cmbSupplier / cmbProduct as JComboBox<String>, so we
    // store the real objects in these lists and map by selected index.
    private final java.util.List<com.mycompany.inventorycontrolsystem.model.Supplier>
            supplierList = new java.util.ArrayList<>();
    private final java.util.List<com.mycompany.inventorycontrolsystem.model.Product>
            productList  = new java.util.ArrayList<>();    private javax.swing.table.DefaultTableModel poItemModel;    private int lastPlacedPoId = -1;
    // BACKEND INITIALISATION  � call from constructor AFTER initComponents()

    /**
     * Wires all backend logic.  Call this from the constructor immediately
     * after {@code initComponents()}.
     */
    public void setupData() {        // Columns: Product | Qty | Unit Cost | Line Total | (hidden productId)
        poItemModel = new javax.swing.table.DefaultTableModel(
                new String[]{"Product", "Qty", "Unit Cost (RM)",
                             "Line Total (RM)", "ProductID"}, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblPOItems.setModel(poItemModel);

        // Hide the internal ProductID column
        tblPOItems.getColumnModel().getColumn(4).setMinWidth(0);
        tblPOItems.getColumnModel().getColumn(4).setMaxWidth(0);
        tblPOItems.getColumnModel().getColumn(4).setWidth(0);

        // Style the table header (dark-navy, consistent with the rest of the app)
        tblPOItems.getTableHeader().setReorderingAllowed(false);
        tblPOItems.getTableHeader().setDefaultRenderer(
                new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable t, Object v, boolean sel,
                    boolean focus, int row, int col) {
                javax.swing.JLabel lbl = (javax.swing.JLabel)
                        super.getTableCellRendererComponent(
                                t, v, sel, focus, row, col);
                lbl.setBackground(new java.awt.Color(24, 35, 54));
                lbl.setForeground(java.awt.Color.WHITE);
                lbl.setFont(new java.awt.Font("Segoe UI",
                        java.awt.Font.BOLD, 13));
                lbl.setHorizontalAlignment(javax.swing.JLabel.CENTER);
                lbl.setOpaque(true);
                return lbl;
            }
        });
        tblPOItems.setRowHeight(28);
        tblPOItems.setFont(new java.awt.Font("Segoe UI",
                java.awt.Font.PLAIN, 13));
        tblPOItems.setGridColor(new java.awt.Color(218, 224, 235));
        tblPOItems.setSelectionBackground(new java.awt.Color(41, 98, 178));
        tblPOItems.setSelectionForeground(java.awt.Color.WHITE);        txtOrderDate.setText(java.time.LocalDate.now().format(DATE_FMT));
        txtOrderDate.setEditable(false);
        txtOrderDate.setBackground(new java.awt.Color(235, 235, 235));        btnPlaceOrder  .addActionListener(e -> btnPlaceOrderActionPerformed());
        btnReceiveStock.addActionListener(e -> btnReceiveStockActionPerformed());
        btnClear       .addActionListener(e -> clearForm());        loadComboBoxes();
    }
    // COMBO BOX POPULATION

    /**
     * Reloads only the product combo box from the database.
     * Called by ProductFrame immediately after a new product is saved,
     * so the Purchase Order screen always has an up-to-date product list.
     */
    public void refreshProductCombo() {
        new javax.swing.SwingWorker<java.util.List<com.mycompany.inventorycontrolsystem.model.Product>, Void>() {
            @Override
            protected java.util.List<com.mycompany.inventorycontrolsystem.model.Product> doInBackground() {
                return productDAO.findAll();
            }
            @Override
            protected void done() {
                try {
                    java.util.List<com.mycompany.inventorycontrolsystem.model.Product> products = get();
                    productList.clear();
                    cmbProduct.removeAllItems();
                    cmbProduct.addItem("-- Select Product --");
                    for (com.mycompany.inventorycontrolsystem.model.Product p : products) {
                        productList.add(p);
                        cmbProduct.addItem(p.getProductCode() + "  " + p.getProductName());
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }.execute();
    }

    private void loadComboBoxes() {
        new javax.swing.SwingWorker<Void, Void>() {
            java.util.List<com.mycompany.inventorycontrolsystem.model.Supplier> suppliers;
            java.util.List<com.mycompany.inventorycontrolsystem.model.Product>  products;

            @Override protected Void doInBackground() {
                suppliers = supplierDAO.findActive();
                products  = productDAO.findAll();
                return null;
            }

            @Override protected void done() {
                try { get(); } catch (Exception ex) {
                    ex.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(
                            PurchaseOrderPanel.this,
                            "Could not load suppliers / products.\n"
                            + "Check database connection.",
                            "Load Error",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Populate cmbSupplier
                supplierList.clear();
                cmbSupplier.removeAllItems();
                cmbSupplier.addItem("-- Select Supplier --");
                for (com.mycompany.inventorycontrolsystem.model.Supplier s
                        : suppliers) {
                    supplierList.add(s);
                    cmbSupplier.addItem(s.getCompanyName());
                }

                // Populate cmbProduct
                productList.clear();
                cmbProduct.removeAllItems();
                cmbProduct.addItem("-- Select Product --");
                for (com.mycompany.inventorycontrolsystem.model.Product p
                        : products) {
                    productList.add(p);
                    cmbProduct.addItem(p.getProductCode()
                            + "  " + p.getProductName());
                }

            }
        }.execute();
    }
    // ADD ITEM  (called by the GEN stub btnAddItemActionPerformed)

    private void addNewItem() {        int productIdx = cmbProduct.getSelectedIndex() - 1; // -1 for placeholder
        if (productIdx < 0) {
            warn("Please select a product."); return;
        }
        com.mycompany.inventorycontrolsystem.model.Product product =
                productList.get(productIdx);        int qty;
        try {
            qty = Integer.parseInt(txtQty.getText().trim());
            if (qty <= 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            warn("Quantity must be a positive whole number.");
            txtQty.requestFocusInWindow();
            return;
        }        java.math.BigDecimal unitCost;
        try {
            unitCost = new java.math.BigDecimal(txtCost.getText().trim());
            if (unitCost.compareTo(java.math.BigDecimal.ZERO) < 0)
                throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            warn("Unit cost must be a valid number (zero or greater).");
            txtCost.requestFocusInWindow();
            return;
        }        for (int row = 0; row < poItemModel.getRowCount(); row++) {
            int existingId = (int) poItemModel.getValueAt(row, 4);
            if (existingId == product.getProductId()) {
                int newQty = (int) poItemModel.getValueAt(row, 1) + qty;
                // Unit cost may be corrected on re-add
                java.math.BigDecimal newTotal =
                        unitCost.multiply(java.math.BigDecimal.valueOf(newQty))
                                .setScale(2, java.math.RoundingMode.HALF_UP);
                
                // setValueAt(Object, int, int) � fix the calls:
                poItemModel.setValueAt(newQty,                            row, 1);
                poItemModel.setValueAt(String.format("%.2f", unitCost),   row, 2);
                poItemModel.setValueAt(String.format("%.2f", newTotal),   row, 3);
                updateTotal();
                resetItemInputs();
                return;
            }
        }        java.math.BigDecimal lineTotal =
                unitCost.multiply(java.math.BigDecimal.valueOf(qty))
                        .setScale(2, java.math.RoundingMode.HALF_UP);
        poItemModel.addRow(new Object[]{
                product.getProductCode() + "  " + product.getProductName(),
                qty,
                String.format("%.2f", unitCost),
                String.format("%.2f", lineTotal),
                product.getProductId()          // hidden column 4
        });

        updateTotal();
        resetItemInputs();
    }

    private void resetItemInputs() {
        cmbProduct.setSelectedIndex(0);
        txtQty.setText("1");
        txtCost.setText("0.00");
    }

    private void updateTotal() {
        java.math.BigDecimal grand = java.math.BigDecimal.ZERO;
        for (int r = 0; r < poItemModel.getRowCount(); r++) {
            grand = grand.add(new java.math.BigDecimal(
                    poItemModel.getValueAt(r, 3).toString()));
        }
        lblGrandTotal.setText(String.format("%.2f", grand));
    }
    // PLACE ORDER

    private void btnPlaceOrderActionPerformed() {        int supplierIdx = cmbSupplier.getSelectedIndex() - 1;
        if (supplierIdx < 0) {
            warn("Please select a supplier."); return;
        }
        if (poItemModel.getRowCount() == 0) {
            warn("Add at least one product before placing the order."); return;
        }

        com.mycompany.inventorycontrolsystem.model.Supplier supplier =
                supplierList.get(supplierIdx);        com.mycompany.inventorycontrolsystem.model.PurchaseOrder po =
                new com.mycompany.inventorycontrolsystem.model.PurchaseOrder();
        po.setSupplierId(supplier.getSupplierId());
        po.setUserId    (currentUser != null ? currentUser.getUserId() : 1);
        po.setPoNumber  (poDAO.generatePoNumber());
        po.setOrderDate (java.time.LocalDate.now());
        po.setStatus    (com.mycompany.inventorycontrolsystem.model
                         .PurchaseOrder.Status.PENDING);
        po.setNotes     ("");

        java.math.BigDecimal grand = java.math.BigDecimal.ZERO;
        for (int r = 0; r < poItemModel.getRowCount(); r++) {
            int    productId = (int) poItemModel.getValueAt(r, 4);
            int    qty       = (int) poItemModel.getValueAt(r, 1);
            java.math.BigDecimal cost = new java.math.BigDecimal(
                    poItemModel.getValueAt(r, 2).toString());

            com.mycompany.inventorycontrolsystem.model.PurchaseOrderItem item =
                    new com.mycompany.inventorycontrolsystem.model.PurchaseOrderItem();
            item.setProductId      (productId);
            item.setQuantityOrdered(qty);
            item.setUnitCost       (cost);
            po.addItem(item);
            grand = grand.add(cost.multiply(java.math.BigDecimal.valueOf(qty)));
        }
        po.setTotalAmount(grand.setScale(2, java.math.RoundingMode.HALF_UP));        btnPlaceOrder.setEnabled(false);
        final com.mycompany.inventorycontrolsystem.model.PurchaseOrder finalPo = po;

        new javax.swing.SwingWorker<Integer, Void>() {
            @Override protected Integer doInBackground() {
                // insertWithItems handles setAutoCommit/commit/rollback
                return poDAO.insertWithItems(finalPo);
            }
            @Override protected void done() {
                btnPlaceOrder.setEnabled(true);
                try {
                    int poId = get();
                    if (poId > 0) {
                        lastPlacedPoId = poId;
                        javax.swing.JOptionPane.showMessageDialog(
                                PurchaseOrderPanel.this,
                                "Purchase Order placed successfully!\n"
                                + "PO Number : " + finalPo.getPoNumber()
                                + "\nPO ID     : " + poId
                                + "\nTotal     : RM " + finalPo.getTotalAmount()
                                + "\n\nClick \"Receive Stock\" when goods arrive.",
                                "Order Placed",
                                javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        clearForm();
                    } else {
                        warn("Failed to save the purchase order.\n"
                           + "Check the application log for the SQL error.");
                    }
                } catch (java.util.concurrent.ExecutionException ex) {
                    ex.printStackTrace();
                    warn("Unexpected error:\n" + ex.getCause().getMessage());
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                }
            }
        }.execute();
    }
    // RECEIVE STOCK

    private void btnReceiveStockActionPerformed() {
        int targetPoId = lastPlacedPoId;

        if (targetPoId <= 0) {
            String input = javax.swing.JOptionPane.showInputDialog(this,
                    "No order was placed in this session.\n"
                    + "Enter the PO ID to receive stock for:",
                    "Receive Stock",
                    javax.swing.JOptionPane.QUESTION_MESSAGE);
            if (input == null || input.trim().isEmpty()) return;
            try {
                targetPoId = Integer.parseInt(input.trim());
            } catch (NumberFormatException ex) {
                warn("PO ID must be a numeric value."); return;
            }
        }

        final int finalPoId = targetPoId;

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Mark PO ID " + finalPoId + " as RECEIVED?\n\n"
                + "This will add the ordered quantities into inventory stock.\n"
                + "This action cannot be undone.",
                "Confirm Receive Stock",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        btnReceiveStock.setEnabled(false);

        new javax.swing.SwingWorker<Boolean, Void>() {
            @Override protected Boolean doInBackground() {
                // receiveOrder handles the full transactional stock upsert:
                // INSERT INTO inventory_stock ... ON DUPLICATE KEY UPDATE
                // quantity_on_hand = quantity_on_hand + ordered_qty
                return poDAO.receiveOrder(finalPoId);
            }
            @Override protected void done() {
                btnReceiveStock.setEnabled(true);
                try {
                    boolean ok = get();
                    if (ok) {
                        lastPlacedPoId = -1;
                        System.out.println("PO ID={} received � stock updated.");
                        javax.swing.JOptionPane.showMessageDialog(
                                PurchaseOrderPanel.this,
                                "Stock received for PO ID: " + finalPoId
                                + "\nInventory has been updated.",
                                "Stock Received",
                                javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        warn("Receive failed for PO ID: " + finalPoId
                           + "\n\nPossible reasons:\n"
                           + "  - PO has no items\n"
                           + "  - PO already marked RECEIVED.");
                    }
                } catch (java.util.concurrent.ExecutionException ex) {
                    ex.printStackTrace();
                    warn("Unexpected error:\n" + ex.getCause().getMessage());
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                }
            }
        }.execute();
    }
    // CLEAR FORM

    public void clearForm() {
        poItemModel.setRowCount(0);
        lblGrandTotal.setText("0.00");
        cmbSupplier.setSelectedIndex(0);
        cmbProduct .setSelectedIndex(0);
        txtQty .setText("1");
        txtCost.setText("0.00");
        txtOrderDate.setText(java.time.LocalDate.now().format(DATE_FMT));
    }
    // UTILITY

    private void warn(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg,
                "Validation", javax.swing.JOptionPane.WARNING_MESSAGE);
    }

} // end class PurchaseOrderPanel


